#!/bin/bash

scp -r client/css gmmapowell@gmmapowell.com:diagram.gmmapowell.com/public
scp client/index.html gmmapowell@gmmapowell.com:diagram.gmmapowell.com/public
scp dist/main.js gmmapowell@gmmapowell.com:diagram.gmmapowell.com/public/js
